using System.Collections.Frozen;

namespace CombatSolver;

internal static partial class StrategicHpRecoveryBound
{
    // Audited native generation closure, enabled only by the separately certified
    // Regent or Ironclad Decimillipede root environments. Combat generation excludes Alchemize, Feed, NotYet and the other
    // CanBeGeneratedInCombat=false cards. Entropy can transform a Splash-generated
    // foreign attack, so the closure includes all five character pools, not just Regent.
    // Generated Osty healing changes the pet, never player HP. Native callback powers,
    // fixed tokens, all generation-eligible native Status/Curse cards, and the five
    // native orbs are included. Ordinary transforms filter Common/Uncommon/Rare;
    // Status/Curse transforms keep their own pools. No generated card gains a run
    // DeckVersion; actual permanent growth cards remain conservative at the bound.
    private static readonly FrozenSet<Type> NativeNonHealingGeneratedCards = new Type[]
    {
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BadLuck),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Beckon),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Clumsy),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.CurseOfTheBell),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Debt),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Decay),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Doubt),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Enthralled),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Folly),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Greed),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Guilty),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Infection),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Injury),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Normality),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.PoorSleep),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Regret),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Shame),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SporeMind),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Toxic),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Wither),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Writhe),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Abrasive), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Accelerant), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Accuracy),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Acrobatics), typeof(global::MegaCrit.Sts2.Core.Models.Cards.AdaptiveStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Adrenaline),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Afterimage), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Afterlife), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Aggression),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Alignment), typeof(global::MegaCrit.Sts2.Core.Models.Cards.AllForOne), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Anger),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Anointed), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Anticipate), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Armaments),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Arsenal), typeof(global::MegaCrit.Sts2.Core.Models.Cards.AshenStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Assassinate),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.AstralPulse), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Automation), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Backflip),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Backstab), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BallLightning), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BansheesCry),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Barrage), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Barricade), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Bash),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BattleTrance), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BeaconOfHope), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BeamCell),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BeatDown), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BeatIntoShape), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Begone),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BelieveInYou), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BiasedCognition), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BigBang),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BlackHole), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BladeDance), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BladeOfInk),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BladeSymphony), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Blaze), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BlightStrike),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BloodWall), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Bloodletting), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Bludgeon),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Blur), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BodySlam), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Bodyguard),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Bolas), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Bombardment), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BoneShards),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BoostAway), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BootSequence), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BorrowedTime),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BouncingFlask), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Brand), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Break),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Breakthrough), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BubbleBubble), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Buffer),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BulkUp), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BulletTime), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Bully),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Bulwark), typeof(global::MegaCrit.Sts2.Core.Models.Cards.BundleOfJoy), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Burn),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.BurningPact), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Burst), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Bury),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Cacophony), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Calamity), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Calcify),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.CalculatedGamble), typeof(global::MegaCrit.Sts2.Core.Models.Cards.CallOfTheVoid), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Capacitor),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.CaptureSpirit), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Cascade), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Catastrophe),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.CelestialMight), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Chaos), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Charge),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.ChargeBattery), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ChildOfTheStars), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Chill),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Cinder), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Claw), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Cleanse),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.CloakAndDagger), typeof(global::MegaCrit.Sts2.Core.Models.Cards.CloakOfStars), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ColdSnap),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.CollisionCourse), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Colossus), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Comet),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Compact), typeof(global::MegaCrit.Sts2.Core.Models.Cards.CompileDriver), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Concoct),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Conflagration), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Conqueror), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Constellation),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.ConsumingShadow), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Convergence), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Coolant),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Coolheaded), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Coordinate), typeof(global::MegaCrit.Sts2.Core.Models.Cards.CorrosiveWave),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Corruption), typeof(global::MegaCrit.Sts2.Core.Models.Cards.CosmicIndifference), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Countdown),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.CrashLanding), typeof(global::MegaCrit.Sts2.Core.Models.Cards.CreativeAi), typeof(global::MegaCrit.Sts2.Core.Models.Cards.CrescentSpear),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.CrimsonMantle), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Cruelty), typeof(global::MegaCrit.Sts2.Core.Models.Cards.CrushUnder),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.DaggerSpray), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DaggerThrow), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DanseMacabre),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.DarkEmbrace), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DarkShackles), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Darkness),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Dash), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Dazed), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DeadlyPoison),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.DeathMarch), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Deathbringer), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DeathsDoor),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Debilitate), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Debris), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DecisionsDecisions),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.DefendDefect), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DefendIronclad), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DefendNecrobinder),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.DefendRegent), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DefendSilent), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Defile),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Deflect), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Defragment), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Defy),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Delay), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Demesne), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DemonForm),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.DemonicShield), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Devastate), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DevourLife),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Dirge), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Discovery), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Dismantle),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.DodgeAndRoll), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Dominate), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DoubleEnergy),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.DrainPower), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DramaticEntrance), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Dredge),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.DrumOfBattle), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Dualcast), typeof(global::MegaCrit.Sts2.Core.Models.Cards.DyingStar),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.EchoForm), typeof(global::MegaCrit.Sts2.Core.Models.Cards.EchoingSlash), typeof(global::MegaCrit.Sts2.Core.Models.Cards.EndOfDays),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.EnergySurge), typeof(global::MegaCrit.Sts2.Core.Models.Cards.EnfeeblingTouch), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Entropy),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Envenom), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Equilibrium), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Eradicate),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.EscapePlan), typeof(global::MegaCrit.Sts2.Core.Models.Cards.EternalArmor), typeof(global::MegaCrit.Sts2.Core.Models.Cards.EvilEye),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.ExpectAFight), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Expertise), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Expose),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Fade), typeof(global::MegaCrit.Sts2.Core.Models.Cards.FallingStar), typeof(global::MegaCrit.Sts2.Core.Models.Cards.FanOfKnives),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Fasten), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Fear), typeof(global::MegaCrit.Sts2.Core.Models.Cards.FeelNoPain),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Feral), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Fetch), typeof(global::MegaCrit.Sts2.Core.Models.Cards.FiendFire),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.FightMe), typeof(global::MegaCrit.Sts2.Core.Models.Cards.FightThrough), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Finesse),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Finisher), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Fisticuffs), typeof(global::MegaCrit.Sts2.Core.Models.Cards.FlakCannon),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.FlameBarrier), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Flanking), typeof(global::MegaCrit.Sts2.Core.Models.Cards.FlashOfSteel),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Flatten), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Flechettes), typeof(global::MegaCrit.Sts2.Core.Models.Cards.FlickFlack),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.FocusedStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Footwork), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ForbiddenGrimoire),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.ForegoneConclusion), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ForgottenRitual), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Friendship),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Ftl), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Fuel), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Furnace),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Fusion), typeof(global::MegaCrit.Sts2.Core.Models.Cards.GammaBlast), typeof(global::MegaCrit.Sts2.Core.Models.Cards.GangUp),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.GatherLight), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Genesis), typeof(global::MegaCrit.Sts2.Core.Models.Cards.GeneticAlgorithm),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.GiantRock), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Glacier), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Glasswork),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Glimmer), typeof(global::MegaCrit.Sts2.Core.Models.Cards.GlimpseBeyond), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Glitterstream),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Glow), typeof(global::MegaCrit.Sts2.Core.Models.Cards.GoForTheEyes), typeof(global::MegaCrit.Sts2.Core.Models.Cards.GoldAxe),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.GrandFinale), typeof(global::MegaCrit.Sts2.Core.Models.Cards.GraveWarden), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Graveblast),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Guards), typeof(global::MegaCrit.Sts2.Core.Models.Cards.GuidingStar), typeof(global::MegaCrit.Sts2.Core.Models.Cards.GunkUp),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Hailstorm), typeof(global::MegaCrit.Sts2.Core.Models.Cards.HammerTime), typeof(global::MegaCrit.Sts2.Core.Models.Cards.HandTrick),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Hang), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Haunt), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Havoc),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Haze), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Headbutt), typeof(global::MegaCrit.Sts2.Core.Models.Cards.HeavenlyDrill),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Hegemony), typeof(global::MegaCrit.Sts2.Core.Models.Cards.HeirloomHammer), typeof(global::MegaCrit.Sts2.Core.Models.Cards.HelixDrill),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Hellraiser), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Hemokinesis), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Hibernate),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.HiddenCache), typeof(global::MegaCrit.Sts2.Core.Models.Cards.HiddenDaggers), typeof(global::MegaCrit.Sts2.Core.Models.Cards.HighFive),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Hologram), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Hotfix), typeof(global::MegaCrit.Sts2.Core.Models.Cards.HowlFromBeyond),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.HuddleUp), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Hyperbeam), typeof(global::MegaCrit.Sts2.Core.Models.Cards.IAmInvincible),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.IceLance), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Ignition), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ImitationLearning),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Impatience), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Impervious), typeof(global::MegaCrit.Sts2.Core.Models.Cards.InfernalBlade),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Inferno), typeof(global::MegaCrit.Sts2.Core.Models.Cards.InfiniteBlades), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Inflame),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Intercept), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Invoke), typeof(global::MegaCrit.Sts2.Core.Models.Cards.IronWave),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Iteration), typeof(global::MegaCrit.Sts2.Core.Models.Cards.JackOfAllTrades), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Jackpot),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Juggernaut), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Juggling), typeof(global::MegaCrit.Sts2.Core.Models.Cards.KinglyKick),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.KinglyPunch), typeof(global::MegaCrit.Sts2.Core.Models.Cards.KnifeTrap), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Knockdown),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.KnockoutBlow), typeof(global::MegaCrit.Sts2.Core.Models.Cards.KnowThyPlace), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Largesse),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.LeadingStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Leap), typeof(global::MegaCrit.Sts2.Core.Models.Cards.LegSweep),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.LegionOfBone), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Lethality), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Lift),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.LightningRod), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Loop), typeof(global::MegaCrit.Sts2.Core.Models.Cards.LunarBlast),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.MachineLearning), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MakeItSo), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Malaise),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Mangle), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ManifestAuthority), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MasterOfStrategy),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.MasterPlanner), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Mayhem), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Melancholy),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.MementoMori), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MeteorShower), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MeteorStrike),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Midnight), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Mimic), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MindBlast),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.MinionDiveBomb), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MinionSacrifice), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MinionStrike),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Mirage), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Misery), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Modded),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.MoltenFist), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MomentumStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MonarchsGaze),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Monologue), typeof(global::MegaCrit.Sts2.Core.Models.Cards.MultiCast), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Murder),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.NecroMastery), typeof(global::MegaCrit.Sts2.Core.Models.Cards.NegativePulse), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Neurosurge),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Neutralize), typeof(global::MegaCrit.Sts2.Core.Models.Cards.NeutronAegis), typeof(global::MegaCrit.Sts2.Core.Models.Cards.NoEscape),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Nostalgia), typeof(global::MegaCrit.Sts2.Core.Models.Cards.NoxiousFumes), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Null),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Oblivion), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Offering), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Omnislice),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.OneForAll), typeof(global::MegaCrit.Sts2.Core.Models.Cards.OneTwoPunch), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Orbit),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Outbreak), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Outrage), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Overclock),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.PactsEnd), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Pagestorm), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PaleBlueDot),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Panache), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PanicButton), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Parry),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Parse), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ParticleWall), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Patter),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.PerfectedStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PhantomBlades), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PhotonCut),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.PiercingWail), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Pillage), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PillarOfCreation),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Pinpoint), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Plot), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PoisonedStab),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Poke), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PommelStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Pounce),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.PreciseCut), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Predator), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PrepTime),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Prepared), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PrimalForce), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Production),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Prolong), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Prophesize), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Protector),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Prowess), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PullAggro), typeof(global::MegaCrit.Sts2.Core.Models.Cards.PullFromBelow),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Purity), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Putrefy), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Pyre),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Quadcast), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Quasar), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Radiate),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Rage), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Rainbow), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Rally),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Rampage), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Rattle), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Reanimate),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Reap), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ReaperForm), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Reave),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Reboot), typeof(global::MegaCrit.Sts2.Core.Models.Cards.RefineBlade), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Reflect),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Reflex), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Refract), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Rend),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Resonance), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Restlessness), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Ricochet),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.RightHandHand), typeof(global::MegaCrit.Sts2.Core.Models.Cards.RocketPunch), typeof(global::MegaCrit.Sts2.Core.Models.Cards.RollingBoulder),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.RoyalGamble), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Rupture), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Sacrifice),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Salvo), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Scavenge), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Scourge),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Scrape), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Scrawl), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SculptingStrike),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Seance), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SecondWind), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SecretTechnique),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SecretWeapon), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SeekerStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SeekingEdge),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SentryMode), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SerpentForm), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SetupStrike),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SevenStars), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Severance), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ShadowShield),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.ShadowStep), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Shadowmeld), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SharedFate),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Shatter), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ShiningStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Shiv),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Shockwave), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Shroud), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ShrugItOff),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SicEm), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Sidestep), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SignalBoost),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Skewer), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Skim), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SleightOfFlesh),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Slice), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Slimed), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Smokestack),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Snakebite), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Snap), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Sneaky),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SolarStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Soul), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SoulStorm),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Soulbound), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SovereignBlade), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Sow),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SpectrumShift), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Speedster), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Spinner),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SpiritOfAsh), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Spite), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Splash),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SpoilsOfBattle), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Spur), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Squeeze),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Stampede), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Stardust), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Stoke),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Stomp), typeof(global::MegaCrit.Sts2.Core.Models.Cards.StoneArmor), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Storm),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.StormOfSteel), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Strangle), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Stratagem),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.StrikeDefect), typeof(global::MegaCrit.Sts2.Core.Models.Cards.StrikeIronclad), typeof(global::MegaCrit.Sts2.Core.Models.Cards.StrikeNecrobinder),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.StrikeRegent), typeof(global::MegaCrit.Sts2.Core.Models.Cards.StrikeSilent), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Subroutine),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SuckerPunch), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SummonForth), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Sunder),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Supercritical), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Supermassive), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Suppress),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Survivor), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SweepingBeam), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SweepingGaze),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.SwordBoomerang), typeof(global::MegaCrit.Sts2.Core.Models.Cards.SwordSage), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Synchronize),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Synthesis), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Tactician), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TagTeam),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Tank), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Taunt), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TearAsunder),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Tempest), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Terraforming), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TeslaCoil),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.TheBall), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TheBomb), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TheGambit),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.TheScythe), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TheSealedThrone), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TheSmith),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.ThinkingAhead), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Thrash), typeof(global::MegaCrit.Sts2.Core.Models.Cards.ThrummingHatchet),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Thunder), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Thunderclap), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TimesUp),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.ToolsOfTheTrade), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Tracking), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TrashToTreasure),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Tremble), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TrueGrit), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Turbo),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Tutor), typeof(global::MegaCrit.Sts2.Core.Models.Cards.TwinStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Tyranny),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.UltimateDefend), typeof(global::MegaCrit.Sts2.Core.Models.Cards.UltimateStrike), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Undeath),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Underworld), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Unleash), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Unmovable),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Unrelenting), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Untouchable), typeof(global::MegaCrit.Sts2.Core.Models.Cards.UpMySleeve),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Uppercut), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Uproar), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Veilpiercer),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Venerate), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Vicious), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Void),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.VoidForm), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Volley), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Voltaic),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.WellLaidPlans), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Whirlwind), typeof(global::MegaCrit.Sts2.Core.Models.Cards.WhiteNoise),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.Wisp), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Wound), typeof(global::MegaCrit.Sts2.Core.Models.Cards.WraithForm),
        typeof(global::MegaCrit.Sts2.Core.Models.Cards.WroughtInWar), typeof(global::MegaCrit.Sts2.Core.Models.Cards.Zap),
    }.ToFrozenSet();

    private static readonly FrozenSet<Type> NativeNonHealingGeneratedPowers = new Type[]
    {
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.AccelerantPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.AccuracyPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.AfterimagePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.AggressionPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.AnticipatePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ArsenalPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.ArtifactPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.AutomationPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.BarricadePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.BeaconOfHopePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.BiasedCognitionPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.BlackHolePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.BlockNextTurnPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.BlurPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.BorrowedTimePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.BufferPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.BurstPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.CacophonyPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.CalamityPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.CalcifyPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.CallOfTheVoidPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.ChildOfTheStarsPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ClarityPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ColossusPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.ConcoctPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ConquerorPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ConsumingShadowPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.CoolantPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.CoordinatePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.CorrosiveWavePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.CorruptionPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.CountdownPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.CoveredPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.CreativeAiPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.CrimsonMantlePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.CrueltyPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.CrushUnderPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.DanseMacabrePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.DarkEmbracePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.DarkShacklesPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.DebilitatePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.DemesnePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.DemonFormPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.DevourLifePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.DexterityPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.DieForYouPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.DoomPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.DoubleDamagePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.DrawCardsNextTurnPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.DyingStarPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.EchoFormPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.EnergyNextTurnPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.EnfeeblingTouchPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.EntropyPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.EnvenomPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.FadePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.FanOfKnivesPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.FastenPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.FeelNoPainPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.FeralPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.FlameBarrierPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.FlankingPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.FocusPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.FocusedStrikePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ForbiddenGrimoirePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ForegoneConclusionPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.FreeAttackPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.FreePowerPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.FreeSkillPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.FriendshipPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.FurnacePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.GenesisPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.GuardedPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.HailstormPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.HammerTimePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.HangPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.HauntPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.HellraiserPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.HibernatePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.HotfixPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.HyperbeamFocusDownPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.ImitationLearningPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.InfernoPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.InfiniteBladesPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.IntangiblePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.InterceptPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.IterationPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.JuggernautPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.JugglingPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.KnockdownPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.LethalityPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.LightningRodPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.LoopPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.MachineLearningPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ManglePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.MasterPlannerPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.MayhemPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.MonarchsGazePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.MonarchsGazeStrengthDownPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.MonologuePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.NecroMasteryPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.NeurosurgePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.NoBlockPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.NoDrawPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.NostalgiaPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.NoxiousFumesPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.OblivionPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.OneForAllPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.OneTwoPunchPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.OrbitPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.PagestormPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.PaleBlueDotPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.PanachePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ParryPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.PhantomBladesPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.PiercingWailPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.PillarOfCreationPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.PlatingPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.PoisonPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.PrepTimePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.PyrePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.RagePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ReaperFormPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.ReflectPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.RetainHandPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.RollingBoulderPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.RupturePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SeekingEdgePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SentryModePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.SerpentFormPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SetupStrikePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ShadowStepPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.ShadowmeldPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ShroudPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SicEmPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.SignalBoostPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SleightOfFleshPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SmokestackPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.SneakyPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SoulboundPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SpectrumShiftPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.SpeedsterPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SpinnerPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SpiritOfAshPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.StampedePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.StarNextTurnPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.StormPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.StranglePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.StratagemPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.StrengthPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.SubroutinePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SummonNextTurnPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.SwordSagePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.SynchronizePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.TagTeamPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.TankPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.TemporaryDexterityPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.TemporaryFocusPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.TemporaryStrengthPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.TheBombPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.TheGambitPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.TheSealedThronePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.ThornsPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ThunderPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.ToolsOfTheTradePower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.TrackingPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.TrashToTreasurePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.TyrannyPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.UnderworldPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.UnmovablePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.VeilpiercerPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.ViciousPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.VigorPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.VoidFormPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.VulnerablePower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.WeakPower), typeof(global::MegaCrit.Sts2.Core.Models.Powers.WellLaidPlansPower),
        typeof(global::MegaCrit.Sts2.Core.Models.Powers.WraithFormPower),
    }.ToFrozenSet();
}
